# Generated by Django 3.0.7 on 2020-06-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoTwo', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivs', models.CharField(max_length=200)),
                ('completeddelivs', models.BooleanField(default=False)),
            ],
        ),
    ]
